apiVersion: v1
kind: Service
metadata:
  namespace: vote
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db-deployment
  type: ClusterIP
status:
  loadBalancer: {}