apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  creationTimestamp: null
  labels:
    app: result-deployment
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: result-deployment
    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:before
        name: examplevotingapp-result-swl4b
        resources: {}
status: {}