apiVersion: v1
kind: Service
metadata:
  namespace: development 
  labels:
    app: jekyll-node-port
  name: jekyll
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30097
    targetPort: 4000
  selector:
    run: jekyll 
  type: NodePort
status:
  loadBalancer: {}
